### ISSUE TITLE
PWA for off line capability

### ISSUE THREAD

**Issue by faithwins** [Ethiopia-COVID19/covid-19-homepage#7]
The project already includes a PWA plugin. It needs to be configured for a better offline capability and so it can be installed on mobile phones.

**Comment by abelhbeyene** [comment]
@faithwins - picking this one up

**Comment by faithwins** [comment]
@abelhbeyene - Okay, great. Most of the staff should already be there with default settings of the Vue PWA plugin that is already part of the project. So, only see if there could be any additional settings.
